{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Spherical Mercator (ESPG:900913) coordinates for lat/lon: \n",
      "(-5427106.591844812, -3311666.9971426865)\n",
      "(47785, 54704)\n",
      "256\n",
      "256\n",
      "Pixel (ESPG:4326) coordinates for lat/lon: \n",
      "(28242372.268305067, 7689086.079977245)\n",
      "(110321, 30035)\n",
      "(-28.497161865234375, -48.753204345703125, -28.49578857421875, -48.7518310546875)\n"
     ]
    }
   ],
   "source": [
    " #!/usr/bin/env python\n",
    "###############################################################################\n",
    "# $Id$\n",
    "#\n",
    "# Project:  GDAL2Tiles, Google Summer of Code 2007 & 2008\n",
    "#           Global Map Tiles Classes\n",
    "# Purpose:  Convert a raster into TMS tiles, create KML SuperOverlay EPSG:4326,\n",
    "#           generate a simple HTML viewers based on Google Maps and OpenLayers\n",
    "# Author:   Klokan Petr Pridal, klokan at klokan dot cz\n",
    "# Web:      http://www.klokan.cz/projects/gdal2tiles/\n",
    "#\n",
    "###############################################################################\n",
    "# Copyright (c) 2008 Klokan Petr Pridal. All rights reserved.\n",
    "#\n",
    "# Permission is hereby granted, free of charge, to any person obtaining a\n",
    "# copy of this software and associated documentation files (the \"Software\"),\n",
    "# to deal in the Software without restriction, including without limitation\n",
    "# the rights to use, copy, modify, merge, publish, distribute, sublicense,\n",
    "# and/or sell copies of the Software, and to permit persons to whom the\n",
    "# Software is furnished to do so, subject to the following conditions:\n",
    "#\n",
    "# The above copyright notice and this permission notice shall be included\n",
    "# in all copies or substantial portions of the Software.\n",
    "#\n",
    "# THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS\n",
    "# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n",
    "# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL\n",
    "# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n",
    "# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING\n",
    "# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER\n",
    "# DEALINGS IN THE SOFTWARE.\n",
    "###############################################################################\n",
    "\n",
    "\"\"\"\n",
    "globalmaptiles.py\n",
    "\n",
    "Global Map Tiles as defined in Tile Map Service (TMS) Profiles\n",
    "==============================================================\n",
    "\n",
    "Functions necessary for generation of global tiles used on the web.\n",
    "It contains classes implementing coordinate conversions for:\n",
    "\n",
    "  - GlobalMercator (based on EPSG:900913 = EPSG:3785)\n",
    "       for Google Maps, Yahoo Maps, Microsoft Maps compatible tiles\n",
    "  - GlobalGeodetic (based on EPSG:4326)\n",
    "       for OpenLayers Base Map and Google Earth compatible tiles\n",
    "\n",
    "More info at:\n",
    "\n",
    "http://wiki.osgeo.org/wiki/Tile_Map_Service_Specification\n",
    "http://wiki.osgeo.org/wiki/WMS_Tiling_Client_Recommendation\n",
    "http://msdn.microsoft.com/en-us/library/bb259689.aspx\n",
    "http://code.google.com/apis/maps/documentation/overlays.html#Google_Maps_Coordinates\n",
    "\n",
    "Created by Klokan Petr Pridal on 2008-07-03.\n",
    "Google Summer of Code 2008, project GDAL2Tiles for OSGEO.\n",
    "\n",
    "In case you use this class in your product, translate it to another language\n",
    "or find it usefull for your project please let me know.\n",
    "My email: klokan at klokan dot cz.\n",
    "I would like to know where it was used.\n",
    "\n",
    "Class is available under the open-source GDAL license (www.gdal.org).\n",
    "\"\"\"\n",
    "\n",
    "import math\n",
    "\n",
    "class GlobalMercator(object):\n",
    "    \"\"\"\n",
    "    TMS Global Mercator Profile\n",
    "    ---------------------------\n",
    "\n",
    "    Functions necessary for generation of tiles in Spherical Mercator projection,\n",
    "    EPSG:900913 (EPSG:gOOglE, Google Maps Global Mercator), EPSG:3785, OSGEO:41001.\n",
    "\n",
    "    Such tiles are compatible with Google Maps, Microsoft Virtual Earth, Yahoo Maps,\n",
    "    UK Ordnance Survey OpenSpace API, ...\n",
    "    and you can overlay them on top of base maps of those web mapping applications.\n",
    "    \n",
    "    Pixel and tile coordinates are in TMS notation (origin [0,0] in bottom-left).\n",
    "\n",
    "    What coordinate conversions do we need for TMS Global Mercator tiles::\n",
    "\n",
    "         LatLon      <->       Meters      <->     Pixels    <->       Tile    \n",
    "\n",
    "     WGS84 coordinates   Spherical Mercator  Pixels in pyramid  Tiles in pyramid\n",
    "         lat/lon            XY in metres     XY pixels Z zoom      XYZ from TMS\n",
    "        EPSG:4326           EPSG:900913                                        \n",
    "         .----.              ---------               --                TMS      \n",
    "        /      \\     <->     |       |     <->     /----/    <->      Google    \n",
    "        \\      /             |       |           /--------/          QuadTree  \n",
    "         -----               ---------         /------------/                  \n",
    "       KML, public         WebMapService         Web Clients      TileMapService\n",
    "\n",
    "    What is the coordinate extent of Earth in EPSG:900913?\n",
    "\n",
    "      [-20037508.342789244, -20037508.342789244, 20037508.342789244, 20037508.342789244]\n",
    "      Constant 20037508.342789244 comes from the circumference of the Earth in meters,\n",
    "      which is 40 thousand kilometers, the coordinate origin is in the middle of extent.\n",
    "      In fact you can calculate the constant as: 2 * math.pi * 6378137 / 2.0\n",
    "      $ echo 180 85 | gdaltransform -s_srs EPSG:4326 -t_srs EPSG:900913\n",
    "      Polar areas with abs(latitude) bigger then 85.05112878 are clipped off.\n",
    "\n",
    "    What are zoom level constants (pixels/meter) for pyramid with EPSG:900913?\n",
    "\n",
    "      whole region is on top of pyramid (zoom=0) covered by 256x256 pixels tile,\n",
    "      every lower zoom level resolution is always divided by two\n",
    "      initialResolution = 20037508.342789244 * 2 / 256 = 156543.03392804062\n",
    "\n",
    "    What is the difference between TMS and Google Maps/QuadTree tile name convention?\n",
    "\n",
    "      The tile raster itself is the same (equal extent, projection, pixel size),\n",
    "      there is just different identification of the same raster tile.\n",
    "      Tiles in TMS are counted from [0,0] in the bottom-left corner, id is XYZ.\n",
    "      Google placed the origin [0,0] to the top-left corner, reference is XYZ.\n",
    "      Microsoft is referencing tiles by a QuadTree name, defined on the website:\n",
    "      http://msdn2.microsoft.com/en-us/library/bb259689.aspx\n",
    "\n",
    "    The lat/lon coordinates are using WGS84 datum, yeh?\n",
    "\n",
    "      Yes, all lat/lon we are mentioning should use WGS84 Geodetic Datum.\n",
    "      Well, the web clients like Google Maps are projecting those coordinates by\n",
    "      Spherical Mercator, so in fact lat/lon coordinates on sphere are treated as if\n",
    "      the were on the WGS84 ellipsoid.\n",
    "    \n",
    "      From MSDN documentation:\n",
    "      To simplify the calculations, we use the spherical form of projection, not\n",
    "      the ellipsoidal form. Since the projection is used only for map display,\n",
    "      and not for displaying numeric coordinates, we don't need the extra precision\n",
    "      of an ellipsoidal projection. The spherical projection causes approximately\n",
    "      0.33 percent scale distortion in the Y direction, which is not visually noticable.\n",
    "\n",
    "    How do I create a raster in EPSG:900913 and convert coordinates with PROJ.4?\n",
    "\n",
    "      You can use standard GIS tools like gdalwarp, cs2cs or gdaltransform.\n",
    "      All of the tools supports -t_srs 'epsg:900913'.\n",
    "\n",
    "      For other GIS programs check the exact definition of the projection:\n",
    "      More info at http://spatialreference.org/ref/user/google-projection/\n",
    "      The same projection is degined as EPSG:3785. WKT definition is in the official\n",
    "      EPSG database.\n",
    "\n",
    "      Proj4 Text:\n",
    "        +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0\n",
    "        +k=1.0 +units=m +nadgrids=@null +no_defs\n",
    "\n",
    "      Human readable WKT format of EPGS:900913:\n",
    "         PROJCS[\"Google Maps Global Mercator\",\n",
    "             GEOGCS[\"WGS 84\",\n",
    "                 DATUM[\"WGS_1984\",\n",
    "                     SPHEROID[\"WGS 84\",6378137,298.2572235630016,\n",
    "                         AUTHORITY[\"EPSG\",\"7030\"]],\n",
    "                     AUTHORITY[\"EPSG\",\"6326\"]],\n",
    "                 PRIMEM[\"Greenwich\",0],\n",
    "                 UNIT[\"degree\",0.0174532925199433],\n",
    "                 AUTHORITY[\"EPSG\",\"4326\"]],\n",
    "             PROJECTION[\"Mercator_1SP\"],\n",
    "             PARAMETER[\"central_meridian\",0],\n",
    "             PARAMETER[\"scale_factor\",1],\n",
    "             PARAMETER[\"false_easting\",0],\n",
    "             PARAMETER[\"false_northing\",0],\n",
    "             UNIT[\"metre\",1,\n",
    "                 AUTHORITY[\"EPSG\",\"9001\"]]]\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, tileSize=256):\n",
    "        \"Initialize the TMS Global Mercator pyramid\"\n",
    "        self.tileSize = tileSize\n",
    "        self.initialResolution = 2 * math.pi * 6378137 / self.tileSize\n",
    "        # 156543.03392804062 for tileSize 256 pixels\n",
    "        self.originShift = 2 * math.pi * 6378137 / 2.0\n",
    "        # 20037508.342789244\n",
    "\n",
    "    def LatLonToMeters(self, lat, lon ):\n",
    "        \"Converts given lat/lon in WGS84 Datum to XY in Spherical Mercator EPSG:900913\"\n",
    "\n",
    "        mx = lon * self.originShift / 180.0\n",
    "        my = math.log( math.tan((90 + lat) * math.pi / 360.0 )) / (math.pi / 180.0)\n",
    "\n",
    "        my = my * self.originShift / 180.0\n",
    "        return mx, my\n",
    "\n",
    "    def MetersToLatLon(self, mx, my ):\n",
    "        \"Converts XY point from Spherical Mercator EPSG:900913 to lat/lon in WGS84 Datum\"\n",
    "\n",
    "        lon = (mx / self.originShift) * 180.0\n",
    "        lat = (my / self.originShift) * 180.0\n",
    "\n",
    "        lat = 180 / math.pi * (2 * math.atan( math.exp( lat * math.pi / 180.0)) - math.pi / 2.0)\n",
    "        return lat, lon\n",
    "\n",
    "    def PixelsToMeters(self, px, py, zoom):\n",
    "        \"Converts pixel coordinates in given zoom level of pyramid to EPSG:900913\"\n",
    "\n",
    "        res = self.Resolution( zoom )\n",
    "        mx = px * res - self.originShift\n",
    "        my = py * res - self.originShift\n",
    "        return mx, my\n",
    "        \n",
    "    def MetersToPixels(self, mx, my, zoom):\n",
    "        \"Converts EPSG:900913 to pyramid pixel coordinates in given zoom level\"\n",
    "                \n",
    "        res = self.Resolution( zoom )\n",
    "        px = (mx + self.originShift) / res\n",
    "        py = (my + self.originShift) / res\n",
    "        return px, py\n",
    "    \n",
    "    def PixelsToTile(self, px, py):\n",
    "        \"Returns a tile covering region in given pixel coordinates\"\n",
    "\n",
    "        tx = int( math.ceil( px / float(self.tileSize) ) - 1 )\n",
    "        ty = int( math.ceil( py / float(self.tileSize) ) - 1 )\n",
    "        return tx, ty\n",
    "\n",
    "    def PixelsToRaster(self, px, py, zoom):\n",
    "        \"Move the origin of pixel coordinates to top-left corner\"\n",
    "        \n",
    "        mapSize = self.tileSize << zoom\n",
    "        return px, mapSize - py\n",
    "        \n",
    "    def MetersToTile(self, mx, my, zoom):\n",
    "        \"Returns tile for given mercator coordinates\"\n",
    "        \n",
    "        px, py = self.MetersToPixels( mx, my, zoom)\n",
    "        return self.PixelsToTile( px, py)\n",
    "\n",
    "    def TileBounds(self, tx, ty, zoom):\n",
    "        \"Returns bounds of the given tile in EPSG:900913 coordinates\"\n",
    "        \n",
    "        minx, miny = self.PixelsToMeters( tx*self.tileSize, ty*self.tileSize, zoom )\n",
    "        maxx, maxy = self.PixelsToMeters( (tx+1)*self.tileSize, (ty+1)*self.tileSize, zoom )\n",
    "        return ( minx, miny, maxx, maxy )\n",
    "\n",
    "    def TileLatLonBounds(self, tx, ty, zoom ):\n",
    "        \"Returns bounds of the given tile in latutude/longitude using WGS84 datum\"\n",
    "\n",
    "        bounds = self.TileBounds( tx, ty, zoom)\n",
    "        minLat, minLon = self.MetersToLatLon(bounds[0], bounds[1])\n",
    "        maxLat, maxLon = self.MetersToLatLon(bounds[2], bounds[3])\n",
    "        \n",
    "        return ( minLat, minLon, maxLat, maxLon )\n",
    "        \n",
    "    def Resolution(self, zoom ):\n",
    "        \"Resolution (meters/pixel) for given zoom level (measured at Equator)\"\n",
    "        \n",
    "        # return (2 * math.pi * 6378137) / (self.tileSize * 2**zoom)\n",
    "        return self.initialResolution / (2**zoom)\n",
    "        \n",
    "    def ZoomForPixelSize(self, pixelSize ):\n",
    "        \"Maximal scaledown zoom of the pyramid closest to the pixelSize.\"\n",
    "        \n",
    "        for i in range(30):\n",
    "            if pixelSize > self.Resolution(i):\n",
    "                return i-1 if i!=0 else 0 # We don't want to scale up\n",
    "\n",
    "    def GoogleTile(self, tx, ty, zoom):\n",
    "        \"Converts TMS tile coordinates to Google Tile coordinates\"\n",
    "        \n",
    "        # coordinate origin is moved from bottom-left to top-left corner of the extent\n",
    "        return tx, (2**zoom - 1) - ty\n",
    "\n",
    "    def QuadTree(self, tx, ty, zoom ):\n",
    "        \"Converts TMS tile coordinates to Microsoft QuadTree\"\n",
    "        \n",
    "        quadKey = \"\"\n",
    "        ty = (2**zoom - 1) - ty\n",
    "        for i in range(zoom, 0, -1):\n",
    "            digit = 0\n",
    "            mask = 1 << (i-1)\n",
    "            if (tx & mask) != 0:\n",
    "                digit += 1\n",
    "            if (ty & mask) != 0:\n",
    "                digit += 2\n",
    "            quadKey += str(digit)\n",
    "            \n",
    "        return quadKey\n",
    "\n",
    "#---------------------\n",
    "\n",
    "class GlobalGeodetic(object):\n",
    "    \"\"\"\n",
    "    TMS Global Geodetic Profile\n",
    "    ---------------------------\n",
    "\n",
    "    Functions necessary for generation of global tiles in Plate Carre projection,\n",
    "    EPSG:4326, \"unprojected profile\".\n",
    "\n",
    "    Such tiles are compatible with Google Earth (as any other EPSG:4326 rasters)\n",
    "    and you can overlay the tiles on top of OpenLayers base map.\n",
    "    \n",
    "    Pixel and tile coordinates are in TMS notation (origin [0,0] in bottom-left).\n",
    "\n",
    "    What coordinate conversions do we need for TMS Global Geodetic tiles?\n",
    "\n",
    "      Global Geodetic tiles are using geodetic coordinates (latitude,longitude)\n",
    "      directly as planar coordinates XY (it is also called Unprojected or Plate\n",
    "      Carre). We need only scaling to pixel pyramid and cutting to tiles.\n",
    "      Pyramid has on top level two tiles, so it is not square but rectangle.\n",
    "      Area [-180,-90,180,90] is scaled to 512x256 pixels.\n",
    "      TMS has coordinate origin (for pixels and tiles) in bottom-left corner.\n",
    "      Rasters are in EPSG:4326 and therefore are compatible with Google Earth.\n",
    "\n",
    "         LatLon      <->      Pixels      <->     Tiles    \n",
    "\n",
    "     WGS84 coordinates   Pixels in pyramid  Tiles in pyramid\n",
    "         lat/lon         XY pixels Z zoom      XYZ from TMS\n",
    "        EPSG:4326                                          \n",
    "         .----.                ----                        \n",
    "        /      \\     <->    /--------/    <->      TMS      \n",
    "        \\      /         /--------------/                  \n",
    "         -----        /--------------------/                \n",
    "       WMS, KML    Web Clients, Google Earth  TileMapService\n",
    "    \"\"\"\n",
    "    tileSize = 256\n",
    "\n",
    "    def __init__(self, tileSize = 256):\n",
    "        self.tileSize = tileSize\n",
    "\n",
    "    def LatLonToPixels(self, lat, lon, zoom):\n",
    "        \"Converts lat/lon to pixel coordinates in given zoom of the EPSG:4326 pyramid\"\n",
    "        print self.tileSize\n",
    "        res = 180.0 / self.tileSize / 2**zoom\n",
    "        px = (180 + lat) / res\n",
    "        py = (90 + lon) / res\n",
    "        return px, py\n",
    "\n",
    "    def PixelsToTile(self, px, py):\n",
    "        \"Returns coordinates of the tile covering region in pixel coordinates\"\n",
    "\n",
    "        tx = int( math.ceil( px / float(self.tileSize) ) - 1 )\n",
    "        ty = int( math.ceil( py / float(self.tileSize) ) - 1 )\n",
    "        return tx, ty\n",
    "\n",
    "    def Resolution(self, zoom ):\n",
    "        \"Resolution (arc/pixel) for given zoom level (measured at Equator)\"\n",
    "        \n",
    "        return 180 / 256.0 / 2**zoom\n",
    "        #return 180 / float( 1 << (8+zoom) )\n",
    "\n",
    "    def TileBounds(self, tx, ty, zoom):\n",
    "        \"Returns bounds of the given tile\"\n",
    "        res = 180.0 / 256.0 / 2.0**zoom\n",
    "        return (\n",
    "            tx*256.0*res - 180.0,\n",
    "            ty*256.0*res - 90.0,\n",
    "            (tx+1)*256.0*res - 180.0,\n",
    "            (ty+1)*256.0*res - 90.0\n",
    "        )\n",
    "\n",
    "  \n",
    "lat = -28.496109\n",
    "lon= -48.752528\n",
    "tz = 17\n",
    "mercator = GlobalMercator()\n",
    "\n",
    "mx, my = mercator.LatLonToMeters( lat, lon )\n",
    "print \"Spherical Mercator (ESPG:900913) coordinates for lat/lon: \"\n",
    "print (mx, my)\n",
    "tminx, tminy = mercator.MetersToTile( mx, my, tz )\n",
    "print (tminx, tminy)\n",
    "\n",
    "mercator = GlobalGeodetic()\n",
    "print mercator.tileSize\n",
    "mx, my = mercator.LatLonToPixels( lat, lon, zoom=tz )\n",
    "print \"Pixel (ESPG:4326) coordinates for lat/lon: \"\n",
    "print (mx, my)\n",
    "tminx, tminy = mercator.PixelsToTile( mx, my )\n",
    "print (tminx, tminy)\n",
    "print mercator.TileBounds(tminx, tminy, tz)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
